### ISSUE TITLE
Write .travis.yml file

### ISSUE THREAD

**Issue by ilveroluca** [phnmnl/wft4galaxy#22]
The latest PR we merged starts to introduce some unit tests.  We need to write a simple `travis.yml` to run them on TravisCI.

**Comment by bgruening** [comment]
I think this can be super-easy by using something like this: https://github.com/bgruening/docker-galaxy-stable/blob/master/.travis.yml#L48 + building your Docker image + running it against the Docker Galaxy.

If I should help with this let me know.
