### ISSUE TITLE
Add optional xunit output

### ISSUE THREAD

**Issue by bgruening** [phnmnl/wft4galaxy#24]
It would be great if you could add an optional [XUnit](https://en.wikipedia.org/wiki/XUnit).
An XUnit-formatted XML would make it easier to integrate in other CI systems or to generate reports as stated in https://github.com/phnmnl/wft4galaxy/issues/1.

For inspiration please see the `nosetests --with-xunit` or `planemo test --test_output_xunit`.

**Comment by kikkomep** [comment]
Resolved via #33
