### ISSUE TITLE
develop and master branch

### ISSUE THREAD

**Issue by bgruening** [phnmnl/wft4galaxy#26]
I found it quite confusing that there is nothing on the master branch. Before you publish it there should be an official release and something on the master branch :)

**Comment by pcm32** [comment]
We should probably make development the default branch, what do you think @ilveroluca @kikkomep ??

**Comment by bgruening** [comment]
@pcm32 I think it is - it's just confusing if you clone the repo and see only a readme on the master branch. I expected dev to be dev and wanted to use stable (master). Maybe that's just me :)

**Comment by kikkomep** [comment]
Resolved via https://github.com/phnmnl/wft4galaxy/commit/e5a6b5e56815f9046d883b9caefd4fca24e8da95
