### ISSUE TITLE
optimizing Docker images

### ISSUE THREAD

**Issue by bgruening** [phnmnl/wft4galaxy#27]
To be honest, I don't get why there are so many different Docker images that seems to offer the same functionality, but they share a lot of the same code and this could probably optimized.
Lines like this https://github.com/phnmnl/wft4galaxy/blob/develop/utils/docker/alpine/minimal/Dockerfile#L23 will increase the image size of your Docker image and you can probably not call this image minimal anymore. `git` seems not to be needed, if you `wget` your tarball - the dev packages can be avoided if you use pre-compiled packages (xref: https://github.com/phnmnl/wft4galaxy/issues/25) for end users.

These lines should be put together to minimize the amount of layers you produce:
https://github.com/phnmnl/wft4galaxy/blob/develop/utils/docker/alpine/minimal/Dockerfile#L39 or simply `ADD` a predefined `.bashrc` file.

**Comment by kikkomep** [comment]
Resolved via #35
