### ISSUE TITLE
enhancing in-line documentation of the change-case example

### ISSUE THREAD

**Issue by bgruening** [phnmnl/wft4galaxy#28]
The change-case example is wonderful simple. It would be great for beginners to annotate [this YAML file](https://github.com/phnmnl/wft4galaxy/blob/develop/examples/change_case/workflow-test.yml) a little bit more.

E.g. it should be more obvious that this https://github.com/phnmnl/wft4galaxy/blob/develop/examples/change_case/workflow-test.yml#L19 is a filename. Maybe add a relative path, file ending and a short comment above.

I assume that the key here: https://github.com/phnmnl/wft4galaxy/blob/develop/examples/change_case/workflow-test.yml#L21 maps to the `label` here https://github.com/phnmnl/wft4galaxy/blob/develop/examples/change_case/workflow.ga#L84. This needs to be written down. Also please explain how to create such a label in your workflow (hand-crafted, UI ...), reference maybe http://wft4galaxy.readthedocs.io/notebooks/1_define_test_suite.html

Moreover, mabye a best practice recommendation how to structure test-data and so on. I would recommend to follow the IUC guidelines for tools in this regard.

**Comment by ilveroluca** [comment]
Good suggestion regarding the self-documenting example.   We've added comments that help the user to modify the example to suite his/her new test case.  Moreover, guidelines to structure test data, we'll add relevant suggestions to the project docs.
