### ISSUE TITLE
Create a test suite from a history

### ISSUE THREAD

**Issue by sneumann** [phnmnl/wft4galaxy#4]
Downloading the Workflow, collecting input and output files and creating the YAML is tedious. 
An existing Galaxy history should contain everything that is required to create a test from a downloaded history, i.e. the workflow itself, and the inputs and the outputs. From that, a YAML could be created that the user would then polish into the desired test suite. Yours, Steffen

**Comment by ilveroluca** [comment]
This feature request is now addressed by the [wft4galaxy-wizard](http://wft4galaxy.readthedocs.io/wizard-tool.html) that has recently been added.  Thanks for the suggestion @sneumann!
