### ISSUE TITLE
Create a tool to easily extract input and output dataset names and tool parameter names from workflow

### ISSUE THREAD

**Issue by ilveroluca** [phnmnl/wft4galaxy#7]
Creating the test definition currently requires the user to open the workflow in Galaxy and find the exact labels/names of the input and output datasets.  The same issue exists for tool parameters, where the user currently has to look up the xml wrapper definition to find the names.

It would be very handy to have a simple command line tool that can extract this data directly from the workflow and generate a `yaml` section for the test definition.

**Comment by sneumann** [comment]
Hi, this is related to #4 Yours, Steffen

**Comment by ilveroluca** [comment]
Yes it is.  See it as an intermediate step :-)

**Comment by ilveroluca** [comment]
This feature request has been made obsolete by the [wft4galaxy-wizard](http://wft4galaxy.readthedocs.io/wizard-tool.html).
